site_name: "FastAPI Reference"
site_description: "API docs for FastAPI"
site_url: "https://pawamoy.github.io/fastapi-ref"
repo_url: "https://github.com/pawamoy/fastapi-ref"
repo_name: "pawamoy/fastapi-ref"
site_dir: "site"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

extra_css:
- css/custom.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
# - callouts:
#     strip_period: no
- footnotes
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: yes

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        selection:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
        rendering:
          show_submodules: no
          show_if_no_docstring: yes
          separate_signature: yes
          docstring_section_style: table
          members_order: alphabetical
          show_category_heading: no
          merge_init_into_class: yes
          show_root_toc_entry: yes
